/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as voteContractSol from "./VoteContract.sol";
export { VotingOption__factory } from "./VotingOption__factory";
