/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as voteContractSol from "./VoteContract.sol";
export type { voteContractSol };
export type { VotingOption } from "./VotingOption";
export * as factories from "./factories";
export type { VotingContract } from "./VoteContract.sol/VotingContract";
export { VotingContract__factory } from "./factories/VoteContract.sol/VotingContract__factory";
export { VotingOption__factory } from "./factories/VotingOption__factory";
