import { PollType } from '@/types';

// export const mockpolls: PollType[] = [
//   {
//     id: 'poll1',
//     title: 'Poll1',
//     creator: 'James',
//     startDate: '11/22/2023',
//     endDate: '11/22/2023',
//     isLive: true,
//     topic: 'ZK',
//     subTopic: 'ZKML',
//     isZuPassRequired: true,
//     description: 'Description',
//   },
//   {
//     id: 'poll1',
//     title: 'Poll1',
//     creator: 'James',
//     startDate: '11/22/2023',
//     endDate: '11/22/2023',
//     isLive: true,
//     topic: 'ZK',
//     subTopic: 'ZKML',
//     isZuPassRequired: true,
//     description: 'Description',
//   },
//   {
//     id: 'poll1',
//     title: 'Poll1',
//     creator: 'James',
//     startDate: '11/22/2023',
//     endDate: '11/22/2023',
//     isLive: true,
//     topic: 'ZK',
//     subTopic: 'ZKML',
//     isZuPassRequired: true,
//     description: 'Description',
//   },
//   {
//     id: 'poll1',
//     title: 'Poll1',
//     creator: 'James',
//     startDate: '11/22/2023',
//     endDate: '11/22/2023',
//     isLive: true,
//     topic: 'ZK',
//     subTopic: 'ZKML',
//     isZuPassRequired: true,
//     description: 'Description',
//   },
//   {
//     id: 'poll1',
//     title: 'Poll1',
//     creator: 'James',
//     startDate: '11/22/2023',
//     endDate: '11/22/2023',
//     isLive: true,
//     topic: 'ZK',
//     subTopic: 'ZKML',
//     isZuPassRequired: true,
//     description: 'Description',
//   },
// ];
